<?php
require_once 'includes/header.php';
require_once 'includes/donaciones.php';
redirigirSiNoAutenticado();
$accion=$_GET['accion']??'listar';
$campanas=obtenerCampanasDonacion($pdo,12);$mis_donaciones=obtenerDonacionesUsuario($pdo,$usuario['id'],10);
?>
<div class="container"><aside class="sidebar"><a href="index.php" class="sidebar-item"><i class="fas fa-home"></i><span>Inicio</span></a><a href="emergencia.php" class="sidebar-item"><i class="fas fa-heartbeat"></i><span>Emergencia</span></a><a href="donaciones.php" class="sidebar-item active"><i class="fas fa-hand-holding-heart"></i><span>Donaciones</span></a></aside><main class="main-content"><div class="donaciones-container"><div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:1.5rem;"><h2 style="color:var(--naranja-principal);"><i class="fas fa-hand-holding-heart"></i> Donaciones</h2><?php if($mis_donaciones): ?><a href="donaciones.php?accion=mis_donaciones" class="btn btn-secondary"><i class="fas fa-history"></i> Mi historial</a><?php endif; ?></div>
<?php if($accion==='mis_donaciones'): ?>
 <div class="historial-donaciones"><h3>Mi historial</h3><?php if($mis_donaciones): ?><div class="donaciones-lista"><?php foreach($mis_donaciones as $d): ?><div class="donacion-item"><div class="donacion-info"><h4><?= htmlspecialchars($d['campana_titulo']) ?></h4><p><i class="fas fa-paw"></i> <?= htmlspecialchars($d['mascota_nombre']) ?></p><p class="donacion-monto">$<?= number_format($d['monto'],2) ?></p><p class="donacion-fecha"><?= date('d M Y',strtotime($d['fecha_donacion'])) ?></p></div><div class="donacion-estado <?= $d['estado'] ?>"><?= ucfirst($d['estado']) ?></div></div><?php endforeach; ?></div><?php else: ?><div class="empty-state"><i class="fas fa-hand-holding-heart" style="font-size:3rem;color:var(--gris-medio);margin-bottom:1rem;"></i><h3>Aún no has donado</h3></div><?php endif; ?><a href="donaciones.php" class="btn btn-primary" style="margin-top:1.5rem;"><i class="fas fa-arrow-left"></i> Volver</a></div>
<?php else: ?>
 <?php if($campanas): ?><div class="campanas-grid"><?php foreach($campanas as $c): ?><div class="campana-card"><div class="campana-header"><h3><?= htmlspecialchars($c['titulo']) ?></h3><p><i class="fas fa-paw"></i> <?= htmlspecialchars($c['mascota_nombre']) ?></p></div><div class="campana-descripcion"><?= htmlspecialchars(substr($c['descripcion'],0,140)) ?>...</div><div class="campana-progreso"><div class="progreso-barra"><div class="progreso-lleno" style="width:<?= min($c['porcentaje_completado'],100) ?>%"></div></div><div class="progreso-texto"><span class="recaudado">$<?= number_format($c['total_donado'],2) ?></span><span class="meta">de $<?= number_format($c['meta'],2) ?></span></div><div class="progreso-porcentaje"><?= number_format($c['porcentaje_completado'],1) ?>%</div></div><div class="campana-acciones"><button class="btn btn-primary" onclick="donarCampana(<?= $c['id'] ?>)"><i class="fas fa-heart"></i> Donar</button><div class="campana-creador"><img src="uploads/<?= htmlspecialchars($c['creador_foto']??'default.jpg') ?>" class="creador-avatar" alt="Creador"><span><?= htmlspecialchars($c['creador_nombre']) ?></span></div></div></div><?php endforeach; ?></div><?php else: ?><div class="empty-state"><i class="fas fa-heart" style="font-size:3rem;color:var(--gris-medio);margin-bottom:1rem;"></i><h3>No hay campañas</h3></div><?php endif; ?>
<?php endif; ?>
</div></main></div>
<div id="modalDonacion" class="modal" style="display:none;"><div class="modal-content"><span class="close-modal" onclick="cerrarModalDonacion()">&times;</span><h2>Donar</h2><div id="contenidoDonacion"></div></div></div>
<style>.donaciones-container{background:#fff;border-radius:var(--borde-radius);padding:2rem;box-shadow:var(--sombra);} .campanas-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:1.5rem;} .campana-card{background:linear-gradient(135deg,rgba(230,126,34,.1),rgba(46,204,113,.1));border-radius:var(--borde-radius);overflow:hidden;box-shadow:var(--sombra);} .campana-header{padding:1.5rem;background:linear-gradient(135deg,var(--naranja-principal),var(--verde-principal));color:#fff;} .campana-progreso{padding:0 1.5rem 1.5rem;} .progreso-barra{height:8px;background:var(--gris-medio);border-radius:4px;margin-bottom:1rem;overflow:hidden;} .progreso-lleno{height:100%;background:linear-gradient(90deg,var(--verde-principal),var(--naranja-principal));} .progreso-texto{display:flex;justify-content:space-between;font-weight:bold;} .campana-acciones{padding:0 1.5rem 1.5rem;display:flex;justify-content:space-between;align-items:center;} .creador-avatar{width:36px;height:36px;border-radius:50%;object-fit:cover;margin-right:.5rem;} .donacion-item{background:#fff;padding:1.5rem;border-radius:var(--borde-radius);margin-bottom:1rem;display:flex;justify-content:space-between;box-shadow:var(--sombra);} .donacion-estado.completado{background:rgba(46,204,113,.2);color:var(--verde-principal);} .donacion-estado.pendiente{background:rgba(241,196,15,.2);color:#f1c40f;} .donacion-estado.fallido{background:rgba(231,76,60,.2);color:var(--naranja-principal);} </style>
<script>function donarCampana(id){fetch('formulario_donacion.php?campana='+id).then(r=>r.text()).then(h=>{document.getElementById('contenidoDonacion').innerHTML=h;document.getElementById('modalDonacion').style.display='block';}).catch(()=>alert('Error al cargar formulario'));} function cerrarModalDonacion(){document.getElementById('modalDonacion').style.display='none';} window.onclick=e=>{const m=document.getElementById('modalDonacion'); if(e.target==m) cerrarModalDonacion();};</script>
</body></html>