<?php
require_once 'includes/header.php';
require_once 'includes/servicios.php';
redirigirSiNoAutenticado();
$categoria_id=(int)($_GET['categoria']??0);$ubicacion=$_GET['ubicacion']??'';$servicio_id=(int)($_GET['servicio']??0);
$categorias=obtenerCategoriasServicios($pdo);$servicios=obtenerServicios($pdo,$categoria_id,$ubicacion,20);
$servicio_detalle=null;$calificacion_usuario=null; if($servicio_id){$st=$pdo->prepare("SELECT s.*,c.nombre as categoria_nombre,c.icono as categoria_icono FROM servicios s JOIN categorias_servicios c ON s.categoria_id=c.id WHERE s.id=? AND s.activo=TRUE");$st->execute([$servicio_id]);$servicio_detalle=$st->fetch(PDO::FETCH_ASSOC); if($servicio_detalle){$calificacion_usuario=obtenerCalificacionUsuario($pdo,$servicio_id,$usuario['id']);}}
$mensaje='';$tipo_mensaje=''; if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['calificar_servicio'])){$calificacion=(int)($_POST['calificacion']??0);$comentario=trim($_POST['comentario']??'');$sid=(int)($_POST['servicio_id']??0); if($sid>0 && $calificacion>=1 && $calificacion<=5){ if(calificarServicio($pdo,$sid,$usuario['id'],$calificacion,$comentario)){ $mensaje='Calificación enviada'; $tipo_mensaje='success'; $calificacion_usuario=obtenerCalificacionUsuario($pdo,$sid,$usuario['id']); } else { $mensaje='Error al calificar'; $tipo_mensaje='error'; } } else { $mensaje='Calificación inválida'; $tipo_mensaje='error'; }}
?>
<div class="container"><aside class="sidebar"><a href="index.php" class="sidebar-item"><i class="fas fa-home"></i><span>Inicio</span></a><a href="servicios.php" class="sidebar-item active"><i class="fas fa-stethoscope"></i><span>Servicios</span></a></aside><main class="main-content"><div class="servicios-container"><h2 style="color:var(--verde-principal);margin-bottom:1.5rem;"><i class="fas fa-stethoscope"></i> Servicios Profesionales</h2><?php if($mensaje):?><div class="alert alert-<?= $tipo_mensaje ?>"><?= htmlspecialchars($mensaje) ?></div><?php endif; ?>
<?php if($servicio_detalle): ?>
 <div class="servicio-detalle"><div class="servicio-header"><div class="servicio-titulo"><h3><?= htmlspecialchars($servicio_detalle['nombre']) ?></h3><p><i class="<?= $servicio_detalle['categoria_icono'] ?>"></i> <?= htmlspecialchars($servicio_detalle['categoria_nombre']) ?></p></div><div class="servicio-calificacion"><div class="calificacion-valor"><?php if($servicio_detalle['total_calificaciones']>0): ?><span class="valor"><?= number_format($servicio_detalle['calificacion'],1) ?></span><div class="estrellas"><?php for($i=1;$i<=5;$i++): ?><i class="fas fa-star <?= $i<=round($servicio_detalle['calificacion'])?'llena':'vacia' ?>"></i><?php endfor; ?></div><span class="total">(<?= $servicio_detalle['total_calificaciones'] ?>)</span><?php else: ?><span class="valor">Sin calificaciones</span><?php endif; ?></div></div></div><div class="servicio-info"><?php if(!empty($servicio_detalle['descripcion'])): ?><div class="servicio-seccion"><h4>Descripción</h4><p><?= nl2br(htmlspecialchars($servicio_detalle['descripcion'])) ?></p></div><?php endif; ?><div class="servicio-seccion"><h4>Ubicación</h4><p><i class="fas fa-map-marker-alt"></i> <?= htmlspecialchars($servicio_detalle['ubicacion']) ?></p></div><div class="servicio-contacto"><?php if($servicio_detalle['telefono']): ?><p><i class="fas fa-phone"></i> <?= htmlspecialchars($servicio_detalle['telefono']) ?></p><?php endif; ?><?php if($servicio_detalle['email']): ?><p><i class="fas fa-envelope"></i> <?= htmlspecialchars($servicio_detalle['email']) ?></p><?php endif; ?><?php if($servicio_detalle['sitio_web']): ?><p><i class="fas fa-globe"></i> <a target="_blank" href="<?= htmlspecialchars($servicio_detalle['sitio_web']) ?>">Sitio web</a></p><?php endif; ?></div></div><div class="servicio-calificar"><h4>Califica este servicio</h4><form method="POST"><input type="hidden" name="servicio_id" value="<?= $servicio_detalle['id'] ?>"><div class="form-group"><label>Calificación:</label><div class="calificacion-input"><?php for($i=5;$i>=1;$i--): ?><input type="radio" id="estrella<?= $i ?>" name="calificacion" value="<?= $i ?>" <?= ($calificacion_usuario && $calificacion_usuario['calificacion']==$i)?'checked':''; ?>><label for="estrella<?= $i ?>" class="estrella-label"><i class="fas fa-star"></i></label><?php endfor; ?></div></div><div class="form-group"><label>Comentario:</label><textarea name="comentario" class="form-control" rows="3"><?= $calificacion_usuario? htmlspecialchars($calificacion_usuario['comentario']) : '' ?></textarea></div><button type="submit" name="calificar_servicio" class="btn btn-primary"><?= $calificacion_usuario? 'Actualizar':'Enviar' ?> calificación</button></form></div><a href="servicios.php" class="btn btn-secondary" style="margin-top:1.5rem;"><i class="fas fa-arrow-left"></i> Volver</a></div>
<?php else: ?>
 <div class="servicios-filtros"><form method="GET"><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:1rem;margin-bottom:1.5rem;"><div class="form-group"><label>Categoría</label><select name="categoria" class="form-control"><option value="">Todas</option><?php foreach($categorias as $cat): ?><option value="<?= $cat['id'] ?>" <?= $categoria_id==$cat['id']?'selected':''; ?>><?= htmlspecialchars($cat['nombre']) ?></option><?php endforeach; ?></select></div><div class="form-group"><label>Ubicación</label><input type="text" name="ubicacion" class="form-control" value="<?= htmlspecialchars($ubicacion) ?>" placeholder="Ciudad..."></div></div><button type="submit" class="btn btn-primary" style="width:100%;"><i class="fas fa-search"></i> Buscar</button></form></div>
 <?php if($servicios): ?><div class="servicios-grid"><?php foreach($servicios as $s): ?><a href="servicios.php?servicio=<?= $s['id'] ?>" class="servicio-card"><div class="servicio-icono"><i class="<?= $s['categoria_icono'] ?>"></i></div><div class="servicio-info"><h4><?= htmlspecialchars($s['nombre']) ?></h4><p class="servicio-categoria"><?= htmlspecialchars($s['categoria_nombre']) ?></p><p class="servicio-ubicacion"><i class="fas fa-map-marker-alt"></i> <?= htmlspecialchars($s['ubicacion']) ?></p><div class="servicio-calificacion-resumen"><?php if($s['total_calificaciones']>0): ?><span class="valor"><?= number_format($s['calificacion'],1) ?></span><span class="total">(<?= $s['total_calificaciones'] ?>)</span><?php else: ?><span class="sin-calificacion">Sin calificaciones</span><?php endif; ?></div></div></a><?php endforeach; ?></div><?php else: ?><div class="empty-state"><i class="fas fa-stethoscope" style="font-size:3rem;color:var(--gris-medio);margin-bottom:1rem;"></i><h3>No se encontraron servicios</h3><p>Prueba con otros filtros</p></div><?php endif; ?>
<?php endif; ?>
</div></main></div>
<style>.servicios-container{background:#fff;border-radius:var(--borde-radius);padding:2rem;box-shadow:var(--sombra);} .servicios-filtros{background:var(--gris-claro);padding:1.5rem;border-radius:var(--borde-radius);margin-bottom:2rem;} .servicios-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:1.5rem;} .servicio-card{background:#fff;border-radius:var(--borde-radius);padding:1.5rem;box-shadow:var(--sombra);text-decoration:none;color:inherit;display:flex;gap:1rem;border:1px solid var(--gris-medio);transition:var(--transicion);} .servicio-card:hover{transform:translateY(-3px);box-shadow:0 6px 20px rgba(0,0,0,.15);border-color:var(--verde-principal);} .servicio-icono{width:50px;height:50px;border-radius:50%;background:rgba(46,204,113,.1);display:flex;align-items:center;justify-content:center;color:var(--verde-principal);font-size:1.2rem;} .servicio-info h4{margin-bottom:.3rem;} .servicio-categoria{font-size:.9rem;color:var(--gris-oscuro);margin-bottom:.5rem;} .servicio-ubicacion{font-size:.9rem;margin-bottom:.5rem;} .servicio-calificacion-resumen .valor{font-weight:bold;color:var(--naranja-principal);} .servicio-calificacion-resumen .sin-calificacion{font-style:italic;color:var(--gris-oscuro);} .servicio-detalle{background:#fff;border-radius:var(--borde-radius);overflow:hidden;box-shadow:var(--sombra);} .servicio-header{display:flex;justify-content:space-between;align-items:flex-start;padding:2rem;background:linear-gradient(135deg,rgba(46,204,113,.1),rgba(230,126,34,.1));} .servicio-calificacion .valor{font-size:2rem;font-weight:bold;color:var(--naranja-principal);} .calificacion-input{display:flex;gap:.5rem;margin:1rem 0;} .calificacion-input input{display:none;} .estrella-label{cursor:pointer;color:var(--gris-medio);font-size:1.5rem;} .estrella-label:hover, .calificacion-input input:checked ~ .estrella-label{color:var(--naranja-principal);} .servicio-calificar{padding:2rem;border-top:1px solid var(--gris-medio);background:var(--gris-claro);} </style>
</body></html>